Add Responsivness to the portfolio Desktop version
Hamdullah-Andar/MyPortfolio pull request #4
Opened 2022-10-07 21:49 UTC by Hamdullah-Andar

## Desktop version Complete Portfolio

- Update CSS
- Add Flex-box
- Add Grid
- Add Media Query

## Thank you for the review

2022-10-07 22:12 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @Hamdullah-Andar 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media0.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Meaningful commit messages ✔️ 
* Professional README file ✔️

## Required Changes:
- [x] The website should look good in all screen sizes, kindly fix the issue that happens in certain screen widths to make your project look awesome across all device sizes 💯 

![Animation](https://user-images.githubusercontent.com/50721479/194669759-3370413c-b0bd-4371-9117-19488f2b2544.gif)


_Kindly check the comments below_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-07 22:12 UTC, ha-manel commented on index.html
>                  <h1 class="heading">I’m Hami
- [ ] Kindly update your headline section for desktop version to make it look as much as possible like Figma. The `width` and text `color` are not the same.

## Your design:
![image](https://user-images.githubusercontent.com/50721479/194668867-5265cedf-bdaf-4c52-a5d6-e036b9c296d3.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/194668882-222b6f82-5e7f-4918-8ea2-a795d016bc21.png)

2022-10-07 22:12 UTC, ha-manel commented on index.html
> +            <main class="main-class">
- [ ] Kindly remove the empty space on the right side of the website 👍 
![Animation](https://user-images.githubusercontent.com/50721479/194669038-47988fbe-0898-407f-a512-e5c6cb13ab66.gif)

2022-10-07 22:12 UTC, ha-manel commented on index.html
>                          <ul class="tonic-title">
- [ ] Kindly follow the Figma design as much as possible, this includes `font-size`, text `color`, and the `background-color` of the technologies badges 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/194669242-10c93a90-e873-499f-a52b-aaec531061e7.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/194669263-9e587e97-915c-44f0-8eab-b4a57f466ba3.png)

2022-10-07 22:12 UTC, ha-manel commented on index.html
>                          <button class="project-button">See Project</button>
- [ ] Kindly add button interaction styles (hover, clicked...) as shown in the Figma design:

![image](https://user-images.githubusercontent.com/50721479/194669346-31ff0395-7c5f-44d3-b3b5-5f9a34de86d9.png)

2022-10-07 22:12 UTC, ha-manel commented on index.html
>                      </h2>
- [ ] Kindly follow the same `font-size` and text `color` as shown on Figma, as well as button interaction styles 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/194669491-fad3dc9c-95a8-4a22-9c4b-90d4e79ccd84.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/194669517-165bb25c-f678-436a-9ae3-95f0c258fa00.png)

2022-10-08 16:05 UTC, mgmediaweb approved these changes
Hi @Hamdullah-Andar , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approved5](https://user-images.githubusercontent.com/41912912/194716745-20026e0a-9602-4293-b1e2-5e0c2bf2edac.gif)

## Highlights 💯 
- Good job following the advice of the previous reviewer ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-08 16:15 UTC, merged